# SPRING
# ======================================================================================================================
spring:
  application:
    name: qabase


# CUSTOM APP
# ======================================================================================================================
web-application:
  base-url: "https://google.com"